### ISSUE TITLE
void load_families() feels weird

### ISSUE THREAD

**Issue by chrzyki** [clld/clld-glottologfamily-plugin#6]
Modifying the database to such a large extent with a `void()` function feels rather weird. Could this be refactored into a function that explicitly returns something that can be written to a DB in, for example, a current `DBSession`?

**Comment by xrotwang** [comment]
I don't fully understand. Should functions with side effects always have return values? `DBSession` will always be current, even if it isn't returned by the function.

**Comment by chrzyki** [comment]
Understood & was explained to me, thanks. :)
